[agent]
command = ". ~/.proxy-on.sh && proxychains4 -q codex --dangerously-bypass-approvals-and-sandbox --model {model}"
model = "gpt-5-codex high"
templates_dir = ".tmuxagent/templates"

[worktree]
root = ".tmuxagent/worktrees"

[tmux]
prefix = "agent-"
bin = "tmux"

[state]
db = "~/.tmux_agent/state.db"
